apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - aws-access-secrets.yaml
  - viewer-tensorboard-template-configmap.yaml

# Replace with your namespace
namespace: kubeflow

patchesStrategicMerge:
  - aws-configurations-patch.yaml

configMapGenerator:
- name: pipeline-aws-parameters
  behavior: merge
  envs:
    - params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: awsSecretName
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.awsSecretName
- name: awsAccessKeySecretKey
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.awsAccessKeySecretKey
- name: awsSecretKeySecretKey
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.awsSecretKeySecretKey

configurations:
- params.yaml